IRProject/urls.py
from django.contrib import admin
from django.urls import path,  include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('phase1/', include('Phase1.urls')),
    path('phase2/', include('Phase2.urls')),
    path('phase3/', include('Phase3.urls')),
]

Phase1/urls.py
from . import views
from django.urls import path

app_name = 'Phase1'

urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    # Preprocess Pages
    path('preprocess_text_page', views.preprocess_text_page, name='preprocess_text_page'),
    path('preprocess_file_page', views.preprocess_file_page, name='preprocess_file_page'),
    # APIs
    path('preprocess_text', views.preprocess_text_api, name='preprocess_text'),
    path('preprocess_file', views.preprocess_file_api, name='preprocess_file'),
    path('progress/', views.progress, name='progress'),
]

core/urls.py
from . import views
from django.urls import path

app_name = 'core'

urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
]

Phase1/models.py
from django.db import models

# Create your models here.

Phase1/views.py
from .Phases import Phase1

import os.path
from django.shortcuts import render
from django.http import JsonResponse
from rest_framework.decorators import api_view

# Creating an instance of Phase1 class
phase_object = Phase1()


def index(request):
    """Renders the home page for Learning Log."""
    return render(request, 'Phase1/index.html')


def preprocess_text_page(request):
    """Renders the text input page."""
    set_initial_state()
    return render(request, 'Phase1/index_compression.html')


def preprocess_file_page(request):
    """Renders the file input page."""
    set_initial_state()
    return render(request, 'Phase1/index_construction.html')


def set_initial_state():
    """Sets the initial state for phase object."""
    phase_object.state = [0, "Starting...", '']


@api_view(['POST'])
def preprocess_text_api(request):
    """API endpoint for text preprocessing."""
    input_text, preprocess_params = get_input_and_params(request)
    set_initial_state()
    result_text = phase_object.preprocess_text(input_text, **preprocess_params)
    return JsonResponse({'status': 'success', 'values': format_results(result_text), 'length': len(result_text.keys())})


@api_view(['POST'])
def preprocess_file_api(request):
    """API endpoint for file preprocessing."""
    input_dir, output_dir, preprocess_params = get_file_input_and_params(request)
    validate, text = validate_directories(input_dir, output_dir)
    if not validate:
        return JsonResponse({'status': 'failed', 'message': text})

    set_initial_state()
    phase_object.preprocess_files(input_directory=input_dir, output_directory=output_dir, **preprocess_params)
    return JsonResponse({'status': 'success'})


@api_view(['GET'])
def progress(request):
    """API endpoint for progress."""
    return JsonResponse({'progress': phase_object.state[0], 'state': get_progress_state()})


def get_input_and_params(request):
    """Extracts input text and preprocessing parameters from request."""
    input_text = request.data.get('text', '')
    preprocess_params = {key: request.data.get(key, False) for key in ['normalize', 'tokenize', 'token_spacing',
                                                                       'remove_stopwords', 'lemmatize', 'stem',
                                                                       'remove_punctuations']}
    return input_text, preprocess_params


def get_file_input_and_params(request):
    """Extracts file input, output directories, and preprocessing parameters from request."""
    input_dir = request.data.get('inputDirPath')
    output_dir = request.data.get('outputDirPath')
    preprocess_params = get_input_and_params(request)[1]
    return input_dir, output_dir, preprocess_params


def validate_directories(input_dir, output_dir):
    """Validates input and output directories."""
    if not all(os.path.isdir(d) for d in [input_dir, output_dir]):
        return False, 'Directories does not exist!'
    if not os.listdir(input_dir):
        return False, 'Input directory is empty!'
    return True, 'All good!'


def format_results(result_text):
    """Formats results for JsonResponse."""
    return {key: ''.join(value) if key == 'normalize' else ' '.join(value) for key, value in result_text.items()}


def get_progress_state():
    """Gets progress state."""
    state = phase_object.state
    return f'{state[2]}/{state[1]}' if state[2] else state[1]

Phase1/templates/Phase1/file_input.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Document Type Declaration and Language -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Phase1</title>
    <!-- Internal Styles -->
    <style>
        /* General Styling */
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #1e1e1e;
            color: #fff;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        /* Container Styling */
        .container {
            width: 80%;
            max-width: 800px; /* Adjusted max-width */
            margin: auto;
            padding: 20px;
            border-radius: 10px;
            background-color: #2a2a2a;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
        }

        /* Heading Styling */
        h2 {
            font-size: 24px;
            margin-bottom: 20px;
            text-align: center;
        }

        /* Label Styling */
        label {
            display: block;
            margin-bottom: 10px;
        }

        /* Checkbox Styling */
        input[type="checkbox"] {
            display: none;
        }

        input[type="checkbox"] + label {
            position: relative;
            padding-left: 30px;
            cursor: pointer;
            font-size: 18px;
        }

        input[type="checkbox"] + label:before {
            content: '';
            position: absolute;
            left: 0;
            top: 2px;
            width: 20px;
            height: 20px;
            background-color: #2a2a2a;
            border: 2px solid #4caf50;
            border-radius: 4px;
        }

        input[type="checkbox"]:checked + label:before {
            background-color: #4caf50;
        }

        /* Button Styling */
        button {
            display: block;
            width: 100%;
            padding: 10px 0;
            margin-top: 20px;
            border: none;
            border-radius: 5px;
            background-color: #4caf50;
            color: #fff;
            font-size: 18px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #45a049;
        }

        button:disabled {
            background-color: #536872;
        }

        /* Progress Container Styling */
        .progress-container {
            position: relative;
            width: 100%;
            height: 30px;
            background-color: #4a4a4a;
            border-radius: 5px;
            margin-top: 20px;
            overflow: hidden;
            display: none;
        }

        /* Progress Bar Styling */
        .progress-bar {
            position: relative;
            z-index: 0;
            width: 0;
            height: 100%;
            background-color: #4caf50;
            text-align: center;
            line-height: 30px;
            color: white;
            transition: width 0.3s ease;
        }

        /* Progress Text Styling */
        .progress-text {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            line-height: 30px;
            text-align: center;
            color: white;
            z-index: 1;
        }

        /* Checkbox Container Styling */
        .checkbox-container {
            margin-bottom: 10px;
        }

        .checkbox-container label {
            display: block;
            margin-bottom: 10px;
        }

        .checkbox-container label {
            margin-right: 20px;
        }

        /* Text Input Styling */
        input[type="text"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: none;
            border-radius: 5px;
            background-color: #454545;
            color: #fff;
            box-sizing: border-box; /* Include padding and border in element's total width and height */
        }

        input[type="text"]::placeholder {
            color: #aaa; /* Placeholder color */
        }
    </style>
</head>
<body>

<div class="container" style="width: 95%">
    <form id="preprocess-form">
        <!-- Directories Input Section -->
        <h2>Directories Input</h2>
        <label for="inputDirPath">Input Directory:</label>
        <input type="text" id="inputDirPath" name="inputDirPath" placeholder="Enter input directory path">

        <label for="outputDirPath">Output Directory:</label>
        <input type="text" id="outputDirPath" name="outputDirPath" placeholder="Enter output directory path">
    </form>

    <!-- Preprocess Button and Progress Bar Section -->
    <button id="process_start" type="button" disabled>Preprocess Files</button>
    <div id="progress-container" class="progress-container">
        <div id="progress-text" class="progress-text"></div>
        <div id="progress-bar" class="progress-bar"></div>
    </div>
</div>

<div class="container" style="width: 15%">
    <!-- Function Checkbox Section -->
    <div class="checkbox-container">
        <h2>Function</h2>
        <!-- Checkboxes for various functions -->
        <input type="checkbox" id="normalize" name="normalize">
        <label for="normalize">Normalize</label>

        <input type="checkbox" id="tokenize" name="tokenize">
        <label for="tokenize">Tokenize</label>

        <input type="checkbox" id="lemmatize" name="lemmatize">
        <label for="lemmatize">Lemmatize</label>

        <input type="checkbox" id="stem" name="stem">
        <label for="stem">Stem</label>

        <input type="checkbox" id="token_spacing" name="token_spacing">
        <label for="token_spacing">Token Spacing</label>

        <input type="checkbox" id="remove_stopwords" name="remove_stopwords">
        <label for="remove_stopwords">Remove Stopwords</label>

        <input type="checkbox" id="remove_punctuations" name="remove_punctuations">
        <label for="remove_punctuations">Remove Punctuations</label>
    </div>
</div>

<!-- External JavaScript Library -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Get necessary elements from the DOM
        const lemmatizeCheckbox = document.getElementById("lemmatize");
        const stemCheckbox = document.getElementById("stem");
        const progressContainer = document.getElementById('progress-container');
        const progressText = document.getElementById('progress-text');
        const progressBar = document.getElementById('progress-bar');
        const processStartBtn = document.getElementById("process_start");
        const form = document.getElementById("preprocess-form");
        const inputDirPath = document.getElementById("inputDirPath");
        const outputDirPath = document.getElementById("outputDirPath")

        // Event listener for lemmatize checkbox
        lemmatizeCheckbox.addEventListener('change', function () {
            if (lemmatizeCheckbox.checked) {
                stemCheckbox.checked = false;
            }
        });
        // Event listener for stem checkbox
        stemCheckbox.addEventListener('change', function () {
            if (stemCheckbox.checked) {
                lemmatizeCheckbox.checked = false;
            }
        });

        // Function to update progress bar
        function updateProgressBar() {
            fetch("{% url 'Phase1:progress' %}")
                .then(response => response.json())
                .then(data => {
                    progressBar.style.width = data.progress + '%';
                    progressText.textContent = data.state + ' ' + data.progress + '%';
                })
                .catch(error => console.error('Error:', error));
        }

        // Function to validate text-inputs and checkboxes
        function validateFields() {
            const inputDir = inputDirPath.value.trim();
            const outputDir = outputDirPath.value.trim();

            let checkboxes = document.querySelectorAll('input[type="checkbox"]');
            let checked = false;
            checkboxes.forEach(function (checkbox) {
                if (checkbox.checked) {
                    checked = true;
                }
            });

            const submitButton = document.querySelector('button[type="button"]');
            submitButton.disabled = !(inputDir !== '' && outputDir !== '' && checked);
        }

        function submitForm() {
            // Call updateProgressBar function every second (you can adjust this interval)
            let timer = setInterval(updateProgressBar, 1000);

            // Manually append checked checkboxes to formData
            let checkboxes = document.querySelectorAll('input[type="checkbox"]:checked');
            let formData = new FormData();
            checkboxes.forEach(function (checkbox) {
                formData.append(checkbox.name, checkbox.value);
            });

            // Add directory names to formData
            formData.append("inputDirPath", inputDirPath.value);
            formData.append("outputDirPath", outputDirPath.value);

            let xhr = new XMLHttpRequest();
            xhr.open("POST", "preprocess_file", true);
            xhr.onreadystatechange = function () {
                if (xhr.readyState === XMLHttpRequest.DONE) {
                    clearInterval(timer);

                    if (xhr.status === 200) {
                        // Handle successful response here
                        let jsonResponse = JSON.parse(xhr.responseText);
                        progressContainer.style.backgroundColor = jsonResponse.status === 'success' ? '#4a4a4a' : 'white';
                        progressText.style.color = jsonResponse.status === 'success' ? 'white' : 'red';

                        if (jsonResponse.status !== 'success') {
                            $('#progress-text').text(jsonResponse.message);
                            console.error('Error:', jsonResponse.message);
                        } else
                            updateProgressBar();

                    } else {
                        // Handle errors here
                        console.error('Error:', xhr.status);
                    }
                }
            };
            $('.progress-container').css('display', 'block');
            xhr.send(formData);
        }

        // Event listeners for button clicks and input changes
        processStartBtn.addEventListener('click', submitForm);
        inputDirPath.addEventListener('input', validateFields);
        outputDirPath.addEventListener('input', validateFields);
        $('input[type="checkbox"]').change(function () {
            validateFields();
        });
    });
</script>
</body>
</html>

Phase1/templates/Phase1/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Phase1</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #1e1e1e;
            color: #fff;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            width: 80%;
            max-width: 800px; /* Adjusted max-width */
            margin: auto;
            padding: 20px;
            border-radius: 10px;
            background-color: #2a2a2a;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
        }

        h2 {
            font-size: 24px;
            margin-bottom: 20px;
            text-align: center;
        }

        label {
            display: block;
            margin-bottom: 10px;
        }

        textarea {
            width: calc(100% - 5px);
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            border: 1px solid #4a4a4a;
            background-color: #2a2a2a;
            color: #fff;
            resize: none;
            box-sizing: border-box;
            direction: ltr;
        }

        input[type="checkbox"] {
            display: none;
        }

        input[type="checkbox"] + label {
            position: relative;
            padding-left: 30px;
            cursor: pointer;
            font-size: 18px;
        }

        input[type="checkbox"] + label:before {
            content: '';
            position: absolute;
            left: 0;
            top: 2px;
            width: 20px;
            height: 20px;
            background-color: #2a2a2a;
            border: 2px solid #4caf50;
            border-radius: 4px;
        }

        input[type="checkbox"]:checked + label:before {
            background-color: #4caf50;
        }

        .button-container {
            display: flex;
            justify-content: space-between;
            margin-top: 20px;
        }

        button {
            width: 48%;
            padding: 10px 0;
            border: none;
            border-radius: 5px;
            background-color: #4caf50;
            color: #fff;
            font-size: 18px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #45a049;
        }

        button:disabled {
            background-color: #536872;
        }

        .progress-container {
            position: relative;
            width: 100%;
            height: 30px;
            background-color: #4a4a4a;
            border-radius: 5px;
            margin-top: 20px;
            overflow: hidden;
            display: none;
        }

        .progress-bar {
            position: relative;
            z-index: 0;
            width: 0;
            height: 100%;
            background-color: #4caf50;
            text-align: center;
            line-height: 30px;
            color: white;
            transition: width 0.3s ease;
        }

        .progress-text {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            line-height: 30px;
            text-align: center;
            color: white;
            z-index: 1;
        }

        #result {
            margin-top: 20px;
            padding: 10px;
            border-radius: 5px;
            background-color: #2a2a2a;
            color: #fff;
            border: 1px solid #4a4a4a;
        }

        .checkbox-container {
            margin-bottom: 10px;
        }

        .checkbox-container label {
            display: block;
            margin-bottom: 10px;
        }

        .checkbox-container label {
            margin-right: 20px;
        }
    </style>
</head>
<body>

<div class="container" style="width: 95%">
    <div class="button-container">
        <button onclick="location.href='{% url 'Phase1:preprocess_text_page' %}'" style="height: 200px; font-size: 50px">Text Input
        </button>
        <button onclick="location.href='{% url 'Phase1:preprocess_file_page' %}'" style="height: 200px; font-size: 50px">File Input
        </button>
    </div>
</div>

</body>
</html>