IRProject/urls.py
from django.contrib import admin
from django.urls import path,  include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('phase1/', include('Phase1.urls')),
    path('phase2/', include('Phase2.urls')),
    path('phase3/', include('Phase3.urls')),
]

Phase1/urls.py
from . import views
from django.urls import path

app_name = 'Phase1'

urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    # Preprocess Pages
    path('preprocess_text_page', views.preprocess_text_page, name='preprocess_text_page'),
    path('preprocess_file_page', views.preprocess_file_page, name='preprocess_file_page'),
    # APIs
    path('preprocess_text', views.preprocess_text_api, name='preprocess_text'),
    path('preprocess_file', views.preprocess_file_api, name='preprocess_file'),
    path('progress/', views.progress, name='progress'),
]

Phase2/urls.py
from . import views
from django.urls import path

app_name = 'Phase2'

urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    # Other Pages
    path('index_construction_page', views.index_construction_page, name='index_construction_page'),
    path('index_compression_page', views.index_compression_page, name='index_compression_page'),
    path('add_document_page', views.add_document_page, name='add_document_page'),
    path('remove_document_page', views.remove_document_page, name='remove_document_page'),
    # APIs
    path('progress/', views.progress, name='progress'),
    path('add_document_single_api', views.add_document_single_api, name='add_document_single_api'),
    path('remove_document_single_api', views.remove_document_single_api, name='remove_document_single_api'),
    path('index_document_api', views.index_document_api, name='index_document_api'),
    path('index_compression_api', views.index_compression_api, name='index_compression_api'),
    ]

Phase3/urls.py
from . import views
from django.urls import path

app_name = 'Phase3'

urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    path('search_retrieve_page', views.search_retrieve_page, name='search_retrieve_page'),
    path('measure_system_page', views.measure_system_page, name='measure_system_page'),
    # APIs
    path('progress/', views.progress, name='progress'),
    path('search_retrieve_api', views.search_retrieve_api, name='search_retrieve_api'),
    path('measure_system_api', views.measure_system_api, name='measure_system_api'),
]

core/urls.py
from . import views
from django.urls import path

app_name = 'core'

urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render


def index(request):
    """Renders the home page for Learning Log."""
    return render(request, 'core/index.html')

core/templates/core/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Phases</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #1e1e1e;
            color: #fff;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            width: 80%;
            max-width: 800px;
            margin: auto;
            padding: 20px;
            border-radius: 10px;
            background-color: #2a2a2a;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
        }

        h2 {
            font-size: 24px;
            margin-bottom: 20px;
            text-align: center;
        }

        label {
            display: block;
            margin-bottom: 10px;
        }

        textarea {
            width: calc(100% - 5px);
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            border: 1px solid #4a4a4a;
            background-color: #2a2a2a;
            color: #fff;
            resize: none;
            box-sizing: border-box;
            direction: ltr;
        }

        input[type="checkbox"] {
            display: none;
        }

        input[type="checkbox"] + label {
            position: relative;
            padding-left: 30px;
            cursor: pointer;
            font-size: 18px;
        }

        input[type="checkbox"] + label:before {
            content: '';
            position: absolute;
            left: 0;
            top: 2px;
            width: 20px;
            height: 20px;
            background-color: #2a2a2a;
            border: 2px solid #4caf50;
            border-radius: 4px;
        }

        input[type="checkbox"]:checked + label:before {
            background-color: #4caf50;
        }

        .button-container {
            display: flex;
            flex-direction: column;
            align-items: stretch;
            margin-top: 20px;
        }

        button {
            width: 100%;
            padding: 10px 0;
            border: none;
            border-radius: 5px;
            background-color: #4caf50;
            color: #fff;
            font-size: 18px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            margin-bottom: 10px;
        }

        button:hover {
            background-color: #45a049;
        }

        button:disabled {
            background-color: #536872;
        }

        .progress-container {
            position: relative;
            width: 100%;
            height: 30px;
            background-color: #4a4a4a;
            border-radius: 5px;
            margin-top: 20px;
            overflow: hidden;
            display: none;
        }

        .progress-bar {
            position: relative;
            z-index: 0;
            width: 0;
            height: 100%;
            background-color: #4caf50;
            text-align: center;
            line-height: 30px;
            color: white;
            transition: width 0.3s ease;
        }

        .progress-text {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            line-height: 30px;
            text-align: center;
            color: white;
            z-index: 1;
        }

        #result {
            margin-top: 20px;
            padding: 10px;
            border-radius: 5px;
            background-color: #2a2a2a;
            color: #fff;
            border: 1px solid #4a4a4a;
        }

        .checkbox-container {
            margin-bottom: 10px;
        }

        .checkbox-container label {
            display: block;
            margin-bottom: 10px;
        }

        .checkbox-container label {
            margin-right: 20px;
        }
    </style>
</head>
<body>

<div class="container" style="width: 95%">
    <div class="button-container">
        <button onclick="location.href='{% url 'Phase1:index' %}'" style="height: 200px; font-size: 50px">Phase 1</button>
        <button onclick="location.href='{% url 'Phase2:index' %}'" style="height: 200px; font-size: 50px">Phase 2</button>
        <button onclick="location.href='{% url 'Phase3:index' %}'" style="height: 200px; font-size: 50px">Phase 3</button>
    </div>
</div>
</body>
</html>