IRProject/urls.py
from django.contrib import admin
from django.urls import path,  include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('phase1/', include('Phase1.urls')),
    path('phase2/', include('Phase2.urls')),
    path('phase3/', include('Phase3.urls')),
]

Phase3/urls.py
from . import views
from django.urls import path

app_name = 'Phase3'

urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    path('search_retrieve_page', views.search_retrieve_page, name='search_retrieve_page'),
    path('measure_system_page', views.measure_system_page, name='measure_system_page'),
    # APIs
    path('progress/', views.progress, name='progress'),
    path('search_retrieve_api', views.search_retrieve_api, name='search_retrieve_api'),
    path('measure_system_api', views.measure_system_api, name='measure_system_api'),
]

core/urls.py
from . import views
from django.urls import path

app_name = 'core'

urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
]

Phase3/models.py
from django.db import models

# Create your models here.

Phase3/views.py
from .Phases import Phase3, part1, part2

from django.shortcuts import render
from django.http import JsonResponse
from rest_framework.decorators import api_view

# Creating an instance of Phase1 class
phase_object = Phase3()
phase_object.load_index()


def set_initial_state():
    """Sets the initial state for phase object."""
    phase_object.state = [0, "Starting...", '']


def index(request):
    """Renders the home page for Learning Log."""
    return render(request, 'Phase3/index.html')


def search_retrieve_page(request):
    """Renders the home page for Learning Log."""
    return render(request, 'Phase3/search_retrieve_page.html')


def measure_system_page(request):
    """Renders the home page for Learning Log."""
    return render(request, 'Phase3/measure_system_page.html')


@api_view(['GET'])
def progress(request):
    """API endpoint for progress."""
    return JsonResponse({'progress': phase_object.state[0], 'state': get_progress_state()})


def get_progress_state():
    """Gets progress state."""
    state = phase_object.state
    return f'{state[2]}/{state[1]}' if state[2] else state[1]


@api_view(['POST'])
def search_retrieve_api(request):
    input_query = request.data.get('inputQuery')

    phase_object.load_index()
    set_initial_state()

    ranked_results, phrase_results, matching_terms = part1(phase_object, input_query)
    ranked_results = [
        f'{i["rank"]}. [{i["doc_id"]}] <a href="file://{i["path"]}">{i["file_name"]}</a> [{i["score"]:.8f}]' for
        i in ranked_results]
    phrase_results = [
        f'{i["rank"]}. [{i["doc_id"]}] <a href="file://{i["path"]}">{i["file_name"]}</a> [{i["score"]:.8f}]' for
        i in phrase_results]
    ranked_str = "<br><br>".join(ranked_results)
    phrase_str = "<br><br>".join(phrase_results)

    return JsonResponse({'status': 'success',
                         'ranked_results_values': ranked_str, 'ranked_results_length': len(ranked_results),
                         'phrase_results_values': phrase_str, 'phrase_results_length': len(phrase_results),
                         'matching_terms_values': "<br>".join(matching_terms),
                         'matching_terms_length': len(matching_terms)
                         })


@api_view(['POST'])
def measure_system_api(request):
    input_query = request.data.get('inputQuery')
    input_query = [i.strip() for i in input_query.split(",")]
    input_response = request.data.get('inputResponse')
    input_response = [i.strip().split("-") for i in input_response.split(",")]

    phase_object.load_index()
    set_initial_state()

    input_queries = dict(zip(input_query, input_response))

    res_returns = part2(phase_object, input_queries)
    ranked_str = f"F-Measure: {res_returns['ranked']['f_measure']}<br><br>MAP: {res_returns['ranked']['map']}"
    phrase_str = f"F-Measure: {res_returns['phrase']['f_measure']}<br><br>MAP: {res_returns['phrase']['map']}"

    return JsonResponse({'status': 'success',
                         'ranked_results_values': ranked_str, 'phrase_results_values': phrase_str,
                         })

Phase3/templates/Phase3/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Phase2</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #1e1e1e;
            color: #fff;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            width: 80%;
            max-width: 800px; /* Adjusted max-width */
            margin: auto;
            padding: 20px;
            border-radius: 10px;
            background-color: #2a2a2a;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
        }

        h2 {
            font-size: 24px;
            margin-bottom: 20px;
            text-align: center;
        }

        label {
            display: block;
            margin-bottom: 10px;
        }

        textarea {
            width: calc(100% - 5px);
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            border: 1px solid #4a4a4a;
            background-color: #2a2a2a;
            color: #fff;
            resize: none;
            box-sizing: border-box;
            direction: ltr;
        }

        input[type="checkbox"] {
            display: none;
        }

        input[type="checkbox"] + label {
            position: relative;
            padding-left: 30px;
            cursor: pointer;
            font-size: 18px;
        }

        input[type="checkbox"] + label:before {
            content: '';
            position: absolute;
            left: 0;
            top: 2px;
            width: 20px;
            height: 20px;
            background-color: #2a2a2a;
            border: 2px solid #E52B50;
            border-radius: 4px;
        }

        input[type="checkbox"]:checked + label:before {
            background-color: #E52B50;
        }

        .button-container {
            display: flex;
            justify-content: space-between;
            margin-top: 20px;
        }

        button {
            width: 48%;
            padding: 10px 0;
            border: none;
            border-radius: 5px;
            background-color: #E52B50;
            color: #fff;
            font-size: 18px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #AF002A;
        }

        button:disabled {
            background-color: #536872;
        }

        .progress-container {
            position: relative;
            width: 100%;
            height: 30px;
            background-color: #4a4a4a;
            border-radius: 5px;
            margin-top: 20px;
            overflow: hidden;
            display: none;
        }

        .progress-bar {
            position: relative;
            z-index: 0;
            width: 0;
            height: 100%;
            background-color: #E52B50;
            text-align: center;
            line-height: 30px;
            color: white;
            transition: width 0.3s ease;
        }

        .progress-text {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            line-height: 30px;
            text-align: center;
            color: white;
            z-index: 1;
        }

        #result {
            margin-top: 20px;
            padding: 10px;
            border-radius: 5px;
            background-color: #2a2a2a;
            color: #fff;
            border: 1px solid #4a4a4a;
        }

        .checkbox-container {
            margin-bottom: 10px;
        }

        .checkbox-container label {
            display: block;
            margin-bottom: 10px;
        }

        .checkbox-container label {
            margin-right: 20px;
        }
    </style>
</head>
<body>

<div class="container" style="width: 95%">
    <div class="button-container">
        <button onclick="location.href='{% url 'Phase3:search_retrieve_page' %}'"
                style="height: 200px; font-size: 40px">Search & Retrieve
        </button>
        <button onclick="location.href='{% url 'Phase3:measure_system_page' %}'"
                style="height: 200px; font-size: 40px">Measure System
        </button>
    </div>
</div>
</body>
</html>

Phase3/templates/Phase3/measure_system_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Document Type Declaration and Language -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Phase3</title>
    <!-- Internal Styles -->
    <style>
        /* Styles for the body */
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #1e1e1e;
            color: #fff;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        /* Styles for the main container */
        .container {
            width: 80%;
            max-width: 800px; /* Adjusted max-width */
            margin: auto;
            padding: 20px;
            border-radius: 10px;
            background-color: #2a2a2a;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
        }

        /* Styles for headings */
        h2 {
            font-size: 24px;
            margin-bottom: 20px;
            text-align: center;
        }

        /* Styles for labels */
        label {
            display: block;
            margin-bottom: 10px;
        }

        /* Styles for textareas */
        textarea {
            width: calc(100% - 5px);
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            border: 1px solid #4a4a4a;
            background-color: #2a2a2a;
            color: #fff;
            resize: none;
            box-sizing: border-box;
            direction: ltr;
        }

        /* Styles for checkboxes */
        input[type="checkbox"] {
            display: none;
        }

        /* Styles for labels associated with checkboxes */
        input[type="checkbox"] + label {
            position: relative;
            padding-left: 30px;
            cursor: pointer;
            font-size: 18px;
        }

        /* Styles for unchecked checkboxes */
        input[type="checkbox"] + label:before {
            content: '';
            position: absolute;
            left: 0;
            top: 2px;
            width: 20px;
            height: 20px;
            background-color: #2a2a2a;
            border: 2px solid #4caf50;
            border-radius: 4px;
        }

        /* Styles for checked checkboxes */
        input[type="checkbox"]:checked + label:before {
            background-color: #4caf50;
        }

        /* Styles for buttons */
        button {
            display: block;
            width: 100%;
            padding: 10px 0;
            margin-top: 20px;
            border: none;
            border-radius: 5px;
            background-color: #4caf50;
            color: #fff;
            font-size: 18px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        /* Styles for button hover state */
        button:hover {
            background-color: #45a049;
        }

        /* Styles for disabled buttons */
        button:disabled {
            background-color: #536872;
        }

        /* Styles for the progress container */
        .progress-container {
            position: relative;
            width: 100%;
            height: 30px;
            background-color: #4a4a4a;
            border-radius: 5px;
            margin-top: 20px;
            overflow: hidden;
            display: none;
        }

        /* Styles for the progress bar */
        .progress-bar {
            position: relative;
            z-index: 0;
            width: 0;
            height: 100%;
            background-color: #4caf50;
            text-align: center;
            line-height: 30px;
            color: white;
            transition: width 0.3s ease;
        }

        /* Styles for the progress text */
        .progress-text {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            line-height: 30px;
            text-align: center;
            color: white;
            z-index: 1;
        }

        /* Styles for labels within checkbox container */
        .checkbox-container label {
            display: block;
            margin-bottom: 10px;
        }

        /* Additional styles for labels within checkbox container */
        .checkbox-container label {
            margin-right: 20px;
        }

        /* Additional styles for buttons within button container */
        .button-container button {
            flex: 1; /* Distribute space evenly */
            margin-right: 5px; /* Add margin between buttons */
        }

        /* Text Input Styling */
        input[type="text"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: none;
            border-radius: 5px;
            background-color: #454545;
            color: #fff;
            box-sizing: border-box; /* Include padding and border in element's total width and height */
        }

        input[type="text"]::placeholder {
            color: #aaa; /* Placeholder color */
        }

        /* Two column layout for results */
        .results-container {
            display: flex;
            justify-content: space-between;
            gap: 20px;
        }

        .result {
            flex: 1;
        }

    </style>
</head>
<body>

<div class="container" style="width: 95%">
    <form id="preprocess-form">
        <!-- Directories Input Section -->
        <h2>Measure System</h2>
        <label for="inputQuery">Queries separated with comma:</label>
        <input type="text" id="inputQuery" name="inputQuery" placeholder="Enter query1, query2, ...">
        <label for="inputResponse">True responses separated with comma:</label>
        <input type="text" id="inputResponse" name="inputResponse" placeholder="Enter r11-r12-r13, r21-r22, ...">
    </form>

    <!-- Preprocess Button and Progress Bar Section -->
    <button id="process_start" type="button" disabled>Search</button>
    <div id="progress-container" class="progress-container">
        <div id="progress-text" class="progress-text"></div>
        <div id="progress-bar" class="progress-bar"></div>
    </div>

    <!-- Results container -->
    <div class="results-container">
        <!-- Result section 1 -->
        <div id="result-section1" class="result" style="display: none;">
            <h2 id="text_result1">Ranked Results</h2>
            <div id="result1" dir="auto"></div>
        </div>

        <!-- Result section 2 -->
        <div id="result-section2" class="result" style="display: none;">
            <h2 id="text_result2">Phrase Results</h2>
            <div id="result2" dir="auto"></div>
        </div>
    </div>
</div>

<!-- External JavaScript Library -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Get necessary elements from the DOM
        const progressContainer = document.getElementById('progress-container');
        const progressText = document.getElementById('progress-text');
        const progressBar = document.getElementById('progress-bar');
        const processStartBtn = document.getElementById("process_start");
        const inputQuery = document.getElementById("inputQuery");
        const inputResponse = document.getElementById("inputResponse");
        const resultSection1 = document.getElementById('result-section1');
        const resultSection2 = document.getElementById('result-section2');
        const resultText1 = document.getElementById("result1");
        const resultText2 = document.getElementById("result2");
        const resultResult1 = document.getElementById("text_result1");
        const resultResult2 = document.getElementById("text_result2");

        // Function to update progress bar
        function updateProgressBar() {
            fetch("{% url 'Phase3:progress' %}")
                .then(response => response.json())
                .then(data => {
                    progressBar.style.width = data.progress + '%';
                    progressText.textContent = data.state + ' ' + data.progress + '%';
                })
                .catch(error => console.error('Error:', error));
        }

        // Function to validate text-inputs
        function validateFields() {
            const input1 = inputQuery.value.trim();
            const input2 = inputResponse.value.trim();

            const submitButton = document.querySelector('button[type="button"]');
            submitButton.disabled = !(input1 !== '' && input2 !== '');
        }

        function submitForm() {
            // Call updateProgressBar function every second (you can adjust this interval)
            let timer = setInterval(updateProgressBar, 1000);
            let results_count;
            let ranked_results_values;

            let formData = new FormData();
            // Add directory names to formData
            formData.append("inputQuery", inputQuery.value);
            formData.append("inputResponse", inputResponse.value);

            let xhr = new XMLHttpRequest();
            xhr.open("POST", "measure_system_api", true);
            xhr.onreadystatechange = function () {
                if (xhr.readyState === XMLHttpRequest.DONE) {
                    clearInterval(timer);

                    if (xhr.status === 200) {
                        // Handle successful response here
                        let jsonResponse = JSON.parse(xhr.responseText);
                        progressContainer.style.backgroundColor = jsonResponse.status === 'success' ? '#4a4a4a' : 'white';
                        progressText.style.color = jsonResponse.status === 'success' ? 'white' : 'red';

                        if (jsonResponse.status === 'success') {
                            let ranked_results_values = jsonResponse.ranked_results_values;
                            let phrase_results_values = jsonResponse.phrase_results_values;

                            resultResult1.style.display = 'none';
                            resultResult2.style.display = 'none';
                            resultText1.innerText = '';
                            resultText2.innerText = '';

                            if (ranked_results_values) {
                                resultSection1.style.display = 'block';
                                resultResult1.style.display = 'block';

                                resultText1.innerHTML = ranked_results_values;
                                $('.progress-container').css('display', 'none');
                            }
                            if (ranked_results_values) {
                                resultSection2.style.display = 'block';
                                resultResult2.style.display = 'block';
                                resultResult2.innerHTML = "Phrase Results"

                                resultText2.innerHTML = phrase_results_values;
                                $('.progress-container').css('display', 'none');
                            }
                            // $('#progress-text').text(jsonResponse.message);
                            // console.error('Error:', jsonResponse.message);
                        } else
                            updateProgressBar();

                    } else {
                        // Handle errors here
                        console.error('Error:', xhr.status);
                    }
                }
            };
            $('.progress-container').css('display', 'block');
            xhr.send(formData);
        }

        // Event listeners for button clicks and input changes
        processStartBtn.addEventListener('click', submitForm);
        inputQuery.addEventListener('input', validateFields);
        inputResponse.addEventListener('input', validateFields);
    });
</script>
</body>
</html>

Phase3/templates/Phase3/test.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

</body>
</html>