IRProject/urls.py
from django.contrib import admin
from django.urls import path,  include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('phase1/', include('Phase1.urls')),
    path('phase2/', include('Phase2.urls')),
    path('phase3/', include('Phase3.urls')),
]

Phase2/urls.py
from . import views
from django.urls import path

app_name = 'Phase2'

urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    # Other Pages
    path('index_construction_page', views.index_construction_page, name='index_construction_page'),
    path('index_compression_page', views.index_compression_page, name='index_compression_page'),
    path('add_document_page', views.add_document_page, name='add_document_page'),
    path('remove_document_page', views.remove_document_page, name='remove_document_page'),
    # APIs
    path('progress/', views.progress, name='progress'),
    path('add_document_single_api', views.add_document_single_api, name='add_document_single_api'),
    path('remove_document_single_api', views.remove_document_single_api, name='remove_document_single_api'),
    path('index_document_api', views.index_document_api, name='index_document_api'),
    path('index_compression_api', views.index_compression_api, name='index_compression_api'),
    ]

core/urls.py
from . import views
from django.urls import path

app_name = 'core'

urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
]

Phase2/models.py
from django.db import models

# Create your models here.

Phase2/views.py
import os
from collections import defaultdict
from time import sleep

from .Phases import Phase2

from django.http import JsonResponse
from django.shortcuts import render
from rest_framework.decorators import api_view

# Creating an instance of Phase1 class
phase_object = Phase2()
phase_object.load_index()


# Create your views here.
def index(request):
    """Renders the home page for Learning Log."""
    return render(request, 'Phase2/index.html')


def index_construction_page(request):
    """Renders the home page for Learning Log."""
    return render(request, 'Phase2/index_construction.html')


def index_compression_page(request):
    """Renders the home page for Learning Log."""
    return render(request, 'Phase2/index_compression.html')


def add_document_page(request):
    """Renders the home page for Learning Log."""
    return render(request, 'Phase2/add_document.html')


def remove_document_page(request):
    """Renders the home page for Learning Log."""
    return render(request, 'Phase2/remove_document.html')


def set_initial_state():
    """Sets the initial state for phase object."""
    phase_object.state = [0, "Starting...", '']


@api_view(['POST'])
def add_document_single_api(request):
    input_dir = request.data.get('inputDirPath')
    doc_id = Phase2.next_doc_id()
    phase_object.file_name[doc_id] = input_dir
    set_initial_state()

    try:
        with open(input_dir, 'r', encoding='utf-8') as file:
            data = file.read()
        phase_object.add_document_single(doc_id, data)
    except IOError as e:
        print(f"Error reading file '{input_dir}': {e}")

    phase_object.save_index()
    return JsonResponse({'status': 'success'})


@api_view(['POST'])
def remove_document_single_api(request):
    doc_id = int(request.data.get('inputDirPath'))
    set_initial_state()

    try:
        with open(phase_object.file_name[doc_id], 'r', encoding='utf-8') as file:
            data = file.read()
        phase_object.remove_document_single(doc_id, data)
    except IOError as e:
        print(f"Error reading file '{phase_object.file_name[doc_id]}': {e}")

    except KeyError as e:
        return JsonResponse({'status': 'error', 'message': f'Can\'t find this document !'})

    phase_object.save_index()
    return JsonResponse({'status': 'success'})


@api_view(['POST'])
def index_document_api(request):
    input_dir = request.data.get('inputDirPath')

    params = {key: request.data.get(key, False) for key in ['non-positional', 'positional', 'wildcard']}
    set_initial_state()

    try:
        inputs = [i for i in os.listdir(input_dir)]
    except OSError as e:
        print(f"Error reading directory {input_dir}: {e}")
        return JsonResponse({'status': 'error', 'message': f'Can\'t find this directory!'})

    done = 0
    process_length = len(inputs)

    # clear previous files
    Phase2.doc_id = 0
    phase_object.file_name = dict()
    phase_object.non_positional_index = defaultdict(set)
    phase_object.positional_index = defaultdict(lambda: defaultdict(list))
    phase_object.wildcard_index = defaultdict(set)

    for x, filename in enumerate(inputs, start=1):
        doc_id = Phase2.next_doc_id()
        phase_object.file_name[doc_id] = os.path.join(input_dir, filename)

        try:
            with open(phase_object.file_name[doc_id], 'r', encoding='utf-8') as file:
                data = file.read()
            phase_object.add_document(doc_id, data, **params)
            phase_object.state_updater(done, process_length, "Adding...")
            done += 1
        except IOError as e:
            print(f"Error reading file '{phase_object.file_name[doc_id]}': {e}")

    phase_object.state_updater(done, process_length, "Done!")
    phase_object.save_index()
    return JsonResponse({'status': 'success'})


@api_view(['POST'])
def index_compression_api(request):
    params = {key: request.data.get(key, False) for key in ['variable_byte', 'gamma']}
    message = []

    # Calculate memory size before compression
    original_size = (
            phase_object.get_memory_size(phase_object.non_positional_index) +
            phase_object.get_memory_size(phase_object.positional_index) +
            phase_object.get_memory_size(phase_object.wildcard_index)
    )
    message.append(f"Original Size: {original_size} bytes")

    if params['variable_byte']:
        # Compress using Variable Byte Encoding
        compressed_index_vb = phase_object.compress_index(method='variable_byte')
        compressed_size_vb = phase_object.get_memory_size(compressed_index_vb)
        message.append(f"Variable Byte Compressed Size: {compressed_size_vb} bytes")

    if params['gamma']:
        # Compress using Gamma Encoding
        compressed_index_gamma = phase_object.compress_index(method='gamma')
        compressed_size_gamma = phase_object.get_memory_size(compressed_index_gamma)
        message.append(f"Gamma Compressed Size: {compressed_size_gamma} bytes")

    return JsonResponse({'status': 'success', 'message': "<br/><br/>".join(message)})


@api_view(['GET'])
def progress(request):
    """API endpoint for progress."""
    return JsonResponse({'progress': phase_object.state[0], 'state': get_progress_state()})


def validate_directories(input_dir, output_dir):
    """Validates input and output directories."""
    if not all(os.path.isdir(d) for d in [input_dir, output_dir]):
        return False, 'Directories does not exist!'
    if not os.listdir(input_dir):
        return False, 'Input directory is empty!'
    return True, 'All good!'


def get_progress_state():
    """Gets progress state."""
    state = phase_object.state
    return f'{state[2]}/{state[1]}' if state[2] else state[1]

Phase2/templates/Phase2/add_document.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Document Type Declaration and Language -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Phase2</title>
    <!-- Internal Styles -->
    <style>
        /* General Styling */
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #1e1e1e;
            color: #fff;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        /* Container Styling */
        .container {
            width: 80%;
            max-width: 800px; /* Adjusted max-width */
            margin: auto;
            padding: 20px;
            border-radius: 10px;
            background-color: #2a2a2a;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
        }

        /* Heading Styling */
        h2 {
            font-size: 24px;
            margin-bottom: 20px;
            text-align: center;
        }

        /* Label Styling */
        label {
            display: block;
            margin-bottom: 10px;
        }


        /* Button Styling */
        button {
            display: block;
            width: 100%;
            padding: 10px 0;
            margin-top: 20px;
            border: none;
            border-radius: 5px;
            background-color: #4caf50;
            color: #fff;
            font-size: 18px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #45a049;
        }

        button:disabled {
            background-color: #536872;
        }

        /* Progress Container Styling */
        .progress-container {
            position: relative;
            width: 100%;
            height: 30px;
            background-color: #4a4a4a;
            border-radius: 5px;
            margin-top: 20px;
            overflow: hidden;
            display: none;
        }

        /* Progress Bar Styling */
        .progress-bar {
            position: relative;
            z-index: 0;
            width: 0;
            height: 100%;
            background-color: #4caf50;
            text-align: center;
            line-height: 30px;
            color: white;
            transition: width 0.3s ease;
        }

        /* Progress Text Styling */
        .progress-text {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            line-height: 30px;
            text-align: center;
            color: white;
            z-index: 1;
        }

        /* Text Input Styling */
        input[type="text"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: none;
            border-radius: 5px;
            background-color: #454545;
            color: #fff;
            box-sizing: border-box; /* Include padding and border in element's total width and height */
        }

        input[type="text"]::placeholder {
            color: #aaa; /* Placeholder color */
        }
    </style>
</head>
<body>

<div class="container" style="width: 95%">
    <form id="preprocess-form">
        <!-- Directories Input Section -->
        <h2>Add Document</h2>
        <label for="inputDirPath">Document Path:</label>
        <input type="text" id="inputDirPath" name="inputDirPath" placeholder="Enter document path here">
    </form>

    <!-- Preprocess Button and Progress Bar Section -->
    <button id="process_start" type="button" disabled>Add Document</button>
    <div id="progress-container" class="progress-container">
        <div id="progress-text" class="progress-text"></div>
        <div id="progress-bar" class="progress-bar"></div>
    </div>
</div>

<!-- External JavaScript Library -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Get necessary elements from the DOM
        const progressContainer = document.getElementById('progress-container');
        const progressText = document.getElementById('progress-text');
        const progressBar = document.getElementById('progress-bar');
        const processStartBtn = document.getElementById("process_start");
        const inputDirPath = document.getElementById("inputDirPath");

        // Function to update progress bar
        function updateProgressBar() {
            fetch("{% url 'Phase2:progress' %}")
                .then(response => response.json())
                .then(data => {
                    progressBar.style.width = data.progress + '%';
                    progressText.textContent = data.state + ' ' + data.progress + '%';
                })
                .catch(error => console.error('Error:', error));
        }

        // Function to validate text-inputs
        function validateFields() {
            const inputDir = inputDirPath.value.trim();

            const submitButton = document.querySelector('button[type="button"]');
            submitButton.disabled = !(inputDir !== '' );
        }

        function submitForm() {
            // Call updateProgressBar function every second (you can adjust this interval)
            let timer = setInterval(updateProgressBar, 1000);

            let formData = new FormData();
            // Add directory names to formData
            formData.append("inputDirPath", inputDirPath.value);

            let xhr = new XMLHttpRequest();
            xhr.open("POST", "add_document_single_api", true);
            xhr.onreadystatechange = function () {
                if (xhr.readyState === XMLHttpRequest.DONE) {
                    clearInterval(timer);

                    if (xhr.status === 200) {
                        // Handle successful response here
                        let jsonResponse = JSON.parse(xhr.responseText);
                        progressContainer.style.backgroundColor = jsonResponse.status === 'success' ? '#4a4a4a' : 'white';
                        progressText.style.color = jsonResponse.status === 'success' ? 'white' : 'red';

                        if (jsonResponse.status !== 'success') {
                            $('#progress-text').text(jsonResponse.message);
                            console.error('Error:', jsonResponse.message);
                        } else
                            updateProgressBar();

                    } else {
                        // Handle errors here
                        console.error('Error:', xhr.status);
                    }
                }
            };
            $('.progress-container').css('display', 'block');
            xhr.send(formData);
        }

        // Event listeners for button clicks and input changes
        processStartBtn.addEventListener('click', submitForm);
        inputDirPath.addEventListener('input', validateFields);
    });
</script>
</body>
</html>

Phase2/templates/Phase2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Phase2</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #1e1e1e;
            color: #fff;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            width: 80%;
            max-width: 800px; /* Adjusted max-width */
            margin: auto;
            padding: 20px;
            border-radius: 10px;
            background-color: #2a2a2a;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
        }

        h2 {
            font-size: 24px;
            margin-bottom: 20px;
            text-align: center;
        }

        label {
            display: block;
            margin-bottom: 10px;
        }

        textarea {
            width: calc(100% - 5px);
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            border: 1px solid #4a4a4a;
            background-color: #2a2a2a;
            color: #fff;
            resize: none;
            box-sizing: border-box;
            direction: ltr;
        }

        input[type="checkbox"] {
            display: none;
        }

        input[type="checkbox"] + label {
            position: relative;
            padding-left: 30px;
            cursor: pointer;
            font-size: 18px;
        }

        input[type="checkbox"] + label:before {
            content: '';
            position: absolute;
            left: 0;
            top: 2px;
            width: 20px;
            height: 20px;
            background-color: #2a2a2a;
            border: 2px solid #4caf50;
            border-radius: 4px;
        }

        input[type="checkbox"]:checked + label:before {
            background-color: #4caf50;
        }

        .button-container {
            display: flex;
            justify-content: space-between;
            margin-top: 20px;
        }

        button {
            width: 48%;
            padding: 10px 0;
            border: none;
            border-radius: 5px;
            background-color: #4caf50;
            color: #fff;
            font-size: 18px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #45a049;
        }

        button:disabled {
            background-color: #536872;
        }

        .progress-container {
            position: relative;
            width: 100%;
            height: 30px;
            background-color: #4a4a4a;
            border-radius: 5px;
            margin-top: 20px;
            overflow: hidden;
            display: none;
        }

        .progress-bar {
            position: relative;
            z-index: 0;
            width: 0;
            height: 100%;
            background-color: #4caf50;
            text-align: center;
            line-height: 30px;
            color: white;
            transition: width 0.3s ease;
        }

        .progress-text {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            line-height: 30px;
            text-align: center;
            color: white;
            z-index: 1;
        }

        #result {
            margin-top: 20px;
            padding: 10px;
            border-radius: 5px;
            background-color: #2a2a2a;
            color: #fff;
            border: 1px solid #4a4a4a;
        }

        .checkbox-container {
            margin-bottom: 10px;
        }

        .checkbox-container label {
            display: block;
            margin-bottom: 10px;
        }

        .checkbox-container label {
            margin-right: 20px;
        }
    </style>
</head>
<body>

<div class="container" style="width: 95%">
    <div class="button-container">
        <button onclick="location.href='{% url 'Phase2:add_document_page' %}'"
                style="height: 200px; font-size: 40px">Add Document
        </button>
        <button onclick="location.href='{% url 'Phase2:remove_document_page' %}'"
                style="height: 200px; font-size: 40px">Remove Document
        </button>
    </div>
    <div class="button-container">
        <button onclick="location.href='{% url 'Phase2:index_construction_page' %}'"
                style="height: 200px; font-size: 40px">Index Construction
        </button>
        <button onclick="location.href='{% url 'Phase2:index_compression_page' %}'"
                style="height: 200px; font-size: 40px">Index Compression
        </button>
    </div>
</div>
</body>
</html>

Phase2/templates/Phase2/index_compression.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Phase2</title>
    <!-- Styling for the HTML document -->
    <style>
        /* Styles for the body */
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #1e1e1e;
            color: #fff;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        /* Styles for the main container */
        .container {
            width: 80%;
            max-width: 800px; /* Adjusted max-width */
            margin: auto;
            padding: 20px;
            border-radius: 10px;
            background-color: #2a2a2a;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.5);
        }

        /* Styles for wider container */
        .wider {
            width: 95%;
        }

        /* Styles for narrower container */
        .narrower {
            width: 15%;
        }

        /* Styles for headings */
        h2 {
            font-size: 24px;
            margin-bottom: 20px;
            text-align: center;
        }

        /* Styles for labels */
        label {
            display: block;
            margin-bottom: 10px;
        }

        /* Styles for textareas */
        textarea {
            width: calc(100% - 5px);
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
            border: 1px solid #4a4a4a;
            background-color: #2a2a2a;
            color: #fff;
            resize: none;
            box-sizing: border-box;
            direction: ltr;
        }

        /* Styles for checkboxes */
        input[type="checkbox"] {
            display: none;
        }

        /* Styles for labels associated with checkboxes */
        input[type="checkbox"] + label {
            position: relative;
            padding-left: 30px;
            cursor: pointer;
            font-size: 18px;
        }

        /* Styles for unchecked checkboxes */
        input[type="checkbox"] + label:before {
            content: '';
            position: absolute;
            left: 0;
            top: 2px;
            width: 20px;
            height: 20px;
            background-color: #2a2a2a;
            border: 2px solid #4caf50;
            border-radius: 4px;
        }

        /* Styles for checked checkboxes */
        input[type="checkbox"]:checked + label:before {
            background-color: #4caf50;
        }

        /* Styles for buttons */
        button {
            display: block;
            width: 100%;
            padding: 10px 0;
            margin-top: 20px;
            border: none;
            border-radius: 5px;
            background-color: #4caf50;
            color: #fff;
            font-size: 18px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        /* Styles for button hover state */
        button:hover {
            background-color: #45a049;
        }

        /* Styles for disabled buttons */
        button:disabled {
            background-color: #536872;
        }

        /* Styles for the progress container */
        .progress-container {
            position: relative;
            width: 100%;
            height: 30px;
            background-color: #4a4a4a;
            border-radius: 5px;
            margin-top: 20px;
            overflow: hidden;
            display: none;
        }

        /* Styles for the progress bar */
        .progress-bar {
            position: relative;
            z-index: 0;
            width: 0;
            height: 100%;
            background-color: #4caf50;
            text-align: center;
            line-height: 30px;
            color: white;
            transition: width 0.3s ease;
        }

        /* Styles for the progress text */
        .progress-text {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            line-height: 30px;
            text-align: center;
            color: white;
            z-index: 1;
        }

        /* Styles for the result section */
        #result-section {
            margin-top: 20px;
            padding: 10px;
            border-radius: 5px;
            background-color: #2a2a2a;
            color: #fff;
            border: 1px solid #4a4a4a;
            display: none;
        }

        /* Styles for the checkbox container */
        .checkbox-container {
            margin-bottom: 10px;
        }

        /* Styles for labels within checkbox container */
        .checkbox-container label {
            display: block;
            margin-bottom: 10px;
        }

        /* Additional styles for labels within checkbox container */
        .checkbox-container label {
            margin-right: 20px;
        }

        /* Styles for button container */
        .button-container {
            display: flex;
            justify-content: space-between;
            margin-top: 10px; /* Add margin between the buttons */
        }

        /* Additional styles for buttons within button container */
        .button-container button {
            flex: 1; /* Distribute space evenly */
            margin-right: 5px; /* Add margin between buttons */
        }
    </style>
</head>
<body>
<!-- Main container for the page content -->
<div class="container wider">
    <form id="preprocess-form">
        <h2>Compression</h2>
        <input type="checkbox" id="variable_byte" name="variable_byte">
        <label for="variable_byte">Variable Byte</label>
        <input type="checkbox" id="gamma" name="gamma">
        <label for="gamma">Gamma</label>
    </form>
    <!-- Container for buttons -->
    <div class="button-container">
        <button id="process_start" type="button" disabled>Start Compression</button>
    </div>
    <!-- Progress container -->
    <div class="progress-container">
        <div id="progress-text" class="progress-text"></div>
        <div id="progress-bar" class="progress-bar"></div>
    </div>
    <!-- Result section -->
    <div id="result-section" style="display: none;">
        <!-- Result Display -->
        <h2 id="text_result">Results</h2>
        <div id="result" dir="auto"></div>
    </div>
</div>

<!-- Include jQuery library -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<!-- JavaScript section -->
<script>
    document.addEventListener('DOMContentLoaded', function () {
        // Get necessary elements from the DOM
        const progressText = document.getElementById('progress-text');
        const progressBar = document.getElementById('progress-bar');
        const resultSection = document.getElementById('result-section');
        const resultText = document.getElementById("result");
        const textResult = document.getElementById("text_result");

        const processStartBtn = document.getElementById("process_start");
        const form = document.getElementById("preprocess-form");
        let check_box_values = [];
        let processed_values = {};
        let processed_count = 0;
        let showing_process_values = 0;

        // Function to update progress bar
        function updateProgressBar() {
            fetch("{% url 'Phase2:progress' %}")
                .then(response => response.json())
                .then(data => {
                    progressBar.style.width = data.progress + '%';
                    progressText.textContent = data.state + ' ' + data.progress + '%';
                })
                .catch(error => console.error('Error:', error));
        }

        // Function to submit the form
        function submitForm() {
            check_box_values = [];
            processed_values = {};
            processed_count = 0;
            showing_process_values = 0;

            document.querySelector('button[type="button"]').disabled = true;
            let timer = setInterval(updateProgressBar, 100);
            let formData = new FormData(form);
            Array.from(document.querySelectorAll('input[type="checkbox"]:checked')).forEach(function (checkbox) {
                formData.append(checkbox.name, checkbox.value);
                check_box_values.push(checkbox.name);
            });

            let xhr = new XMLHttpRequest();
            xhr.open("POST", "index_compression_api", true);
            xhr.onreadystatechange = function () {
                var message;
                if (xhr.readyState === XMLHttpRequest.DONE) {
                    clearInterval(timer);
                    if (xhr.status === 200) {
                        let jsonResponse = JSON.parse(xhr.responseText);
                        if (jsonResponse.status === 'success') {
                            // processed_count = jsonResponse.length;
                            // if (processed_count) {
                            message = jsonResponse.message;
                            resultText.innerHTML = message;
                            // textResult.innerHTML = "Text Results (" + title.replace("_", " ").toTitleCase() + ")";
                            resultSection.style.display = 'block';
                            $('.progress-container').css('display', 'none');

                            // } else {
                            //     resultText.innerText = '';
                            //     resultSection.style.display = 'none';
                            // }
                            updateProgressBar();
                        } else {
                            console.error('Error:', jsonResponse.status);
                        }
                    } else {
                        console.error('Error:', xhr.status);
                    }
                    processStartBtn.innerHTML = "Start New Text Process";
                    document.querySelector('button[type="button"]').disabled = false;
                }
            };
            resultSection.style.display = 'none';
            $('.progress-container').css('display', 'block');
            xhr.send(formData);
        }

        // Function for next step in processing
        function nextStep() {
            showing_process_values += 1;
            if (showing_process_values >= processed_count) {
                showing_process_values = 0;
            }
            const title = check_box_values[showing_process_values];
            textResult.innerHTML = "Text Results (" + title.replace("_", " ").toTitleCase() + ")";
            resultText.innerHTML = processed_values[title];
        }

        // Function to validate form fields
        function validateFields() {
            const checkboxes = document.querySelectorAll('input[type="checkbox"]');
            let checked = false;
            checkboxes.forEach(function (checkbox) {
                if (checkbox.checked) {
                    checked = true;
                }
            });
            const submitButton = document.querySelector('button[type="button"]');
            submitButton.disabled = !(checked);
        }

        // Prototype function to convert string to title case
        String.prototype.toTitleCase = function () {
            return this.replace(/\w\S*/g, function (txt) {
                return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();
            });
        };
        // Event listeners for button clicks and input changes
        processStartBtn.addEventListener('click', submitForm);
        $('input[type="checkbox"]').change(function () {
            validateFields();
        });
    });
</script>
</body>
</html>